version: '3.8'
services:
  web:
    build:
      context: .
    container_name: nbp-exchange-api
    ports:
      - "80:8080"
    environment:
      DB_USER: root
      DB_PASSWORD: superStrongPassword
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: exchangeDb
    depends_on:
      - db
    networks:
      - main
  db:
    image: mysql:8.0.29-debian
    container_name: nbp-exchange-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: superStrongPassword
      MYSQL_DATABASE: exchangeDb
    volumes:
      - nbpExchangeDb:/mysql/
    networks:
      - main
volumes:
  nbpExchangeDb:
networks:
  main: