version: '3.8'
services:
  nbp-exchange-api-db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: exchangeDb
    volumes:
      - nbpExchangeDb:/mysql/
volumes:
  nbpExchangeDb: