spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: rootpass
