spring:
  sql:
    init:
      mode: always
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  cache:
    type: simple
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}