spring:
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
  datasource:
    username: root
    password: rootpass
    url: jdbc:mysql://localhost:3306/exchangeDb
