spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  cache:
    type: simple
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver